<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net9.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);MSB3277</NoWarn>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AutoSettingUI.Avalonia.CrossPlatform.Demo\AutoSettingUI.Avalonia.CrossPlatform.Demo.csproj"/>
    </ItemGroup>

</Project>
