<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AssemblyName>AutoSettingUI.WPF.Demo</AssemblyName>
        <RootNamespace>AutoSettingUI.WPF.Demo</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AutoSettingUI.Core\AutoSettingUI.Core.csproj" />
        <ProjectReference Include="..\AutoSettingUI.WPF\AutoSettingUI.WPF.csproj" />
    </ItemGroup>

</Project>
