<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <IsAotCompatible>true</IsAotCompatible>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <!-- Explicit AOT properties to help the SDK -->
        <PublishAot>true</PublishAot>
        <PublishSelfContained>true</PublishSelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <TrimMode>partial</TrimMode>
        <StackTraceSupport>false</StackTraceSupport>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.7"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.2.7"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.7"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.7"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.7">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\AutoSettingUI.Core\AutoSettingUI.Core.csproj" />
      <ProjectReference Include="..\..\src\Extensions\AutoSettingUI.Avalonia\AutoSettingUI.Avalonia.csproj" />
      <ProjectReference Include="..\..\src\AutoSettingUI.Generator\AutoSettingUI.Generator.csproj" 
                        OutputItemType="Analyzer" 
                        ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>
