<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <IsAotCompatible>true</IsAotCompatible>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\AutoSettingUI.Core\AutoSettingUI.Core.csproj" />
      <ProjectReference Include="..\..\AutoSettingUI.Generator\AutoSettingUI.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
