using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AutoSettingUI.Generator.Incremental;

/// <summary>
/// Incremental source generator for AutoSettingUI.
/// Generates <c>GeneratedSettingProvider</c> that implements <c>ISettingDescriptorProvider</c>
/// and <c>IPropertyValueAccessor</c> without runtime reflection, enabling full AOT compatibility.
/// </summary>
[Generator]
public class AutoSettingGenerator : IIncrementalGenerator
{
    private const string SettingUIAttributeName = "SettingUIAttribute";
    private const string HideAttributeName = "HideAttribute";
    private const string TitleAttributeName = "TitleAttribute";
    private const string MainHeaderAttributeName = "MainHeaderAttribute";
    private const string SubHeaderAttributeName = "SubHeaderAttribute";
    private const string RangeAttributeName = "RangeAttribute";
    private const string ItemsSourceAttributeName = "ItemsSourceAttribute";
    private const string ControlBindingAttributeName = "ControlBindingAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
        if (symbol == null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == SettingUIAttributeName)
                return symbol;
        }
        return null;
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol?> classes,
        SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty) return;

        // Deduplicate while preserving type
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var distinctClasses = new List<INamedTypeSymbol>();
        foreach (var c in classes)
        {
            if (c == null) continue;
            var key = c.ToDisplayString();
            if (seen.Add(key))
                distinctClasses.Add(c);
        }

        if (distinctClasses.Count == 0) return;

        var code = GenerateProviderCode(distinctClasses);
        context.AddSource("GeneratedSettingProvider.g.cs", SourceText.From(code, Encoding.UTF8));
    }

    private static string GenerateProviderCode(List<INamedTypeSymbol> classes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using AutoSettingUI.Core.Interfaces;");
        sb.AppendLine("using AutoSettingUI.Core.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoSettingUI.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Source-generated setting descriptor provider. AOT-safe; no runtime reflection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class GeneratedSettingProvider : ISettingDescriptorProvider, IPropertyValueAccessor");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly Dictionary<string, SettingClassDescriptor> _descriptors");
        sb.AppendLine("            = new Dictionary<string, SettingClassDescriptor>();");
        sb.AppendLine();

        // Constructor
        sb.AppendLine("        public GeneratedSettingProvider()");
        sb.AppendLine("        {");
        foreach (var cls in classes)
            sb.AppendLine($"            Register_{EscapeName(cls.Name)}();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ISettingDescriptorProvider
        sb.AppendLine("        public SettingClassDescriptor? GetDescriptor(Type type)");
        sb.AppendLine("            => GetDescriptor(type.FullName ?? type.Name);");
        sb.AppendLine();
        sb.AppendLine("        public SettingClassDescriptor? GetDescriptor(string typeName)");
        sb.AppendLine("        {");
        sb.AppendLine("            _descriptors.TryGetValue(typeName, out var d);");
        sb.AppendLine("            return d;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public IReadOnlyList<SettingClassDescriptor> GetAllDescriptors()");
        sb.AppendLine("            => new List<SettingClassDescriptor>(_descriptors.Values);");
        sb.AppendLine();
        sb.AppendLine("        public bool HasDescriptor(Type type)");
        sb.AppendLine("            => HasDescriptor(type.FullName ?? type.Name);");
        sb.AppendLine();
        sb.AppendLine("        public bool HasDescriptor(string typeName)");
        sb.AppendLine("            => _descriptors.ContainsKey(typeName);");
        sb.AppendLine();

        // IPropertyValueAccessor – GetValue
        sb.AppendLine("        public object? GetValue(object target, string propertyName)");
        sb.AppendLine("        {");
        foreach (var cls in classes)
        {
            var fqn = cls.ToDisplayString();
            sb.AppendLine($"            if (target is {fqn} t_{EscapeName(cls.Name)})");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (propertyName)");
            sb.AppendLine("                {");
            foreach (var prop in GetPublicInstanceProperties(cls))
                sb.AppendLine($"                    case \"{prop.Name}\": return t_{EscapeName(cls.Name)}.{prop.Name};");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // IPropertyValueAccessor – SetValue
        sb.AppendLine("        public void SetValue(object target, string propertyName, object? value)");
        sb.AppendLine("        {");
        foreach (var cls in classes)
        {
            var fqn = cls.ToDisplayString();
            var escapedName = EscapeName(cls.Name);
            sb.AppendLine($"            if (target is {fqn} s_{escapedName})");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (propertyName)");
            sb.AppendLine("                {");
            foreach (var prop in GetPublicInstanceProperties(cls))
            {
                if (prop.SetMethod != null && prop.SetMethod.DeclaredAccessibility == Accessibility.Public)
                {
                    var typeFqn = prop.Type.ToDisplayString();
                    sb.AppendLine($"                    case \"{prop.Name}\": s_{escapedName}.{prop.Name} = ({typeFqn})value!; return;");
                }
            }
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        // Per-class registration methods
        foreach (var cls in classes)
            AppendRegisterMethod(sb, cls);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendRegisterMethod(StringBuilder sb, INamedTypeSymbol cls)
    {
        var fqn = cls.ToDisplayString();
        var safeName = EscapeName(cls.Name);

        var settingAttr = GetAttr(cls, SettingUIAttributeName);
        var mainHeaderAttr = GetAttr(cls, MainHeaderAttributeName);

        var category = GetNamedArgString(settingAttr, "Category");
        var orderRaw = settingAttr?.NamedArguments.FirstOrDefault(a => a.Key == "Order").Value.Value;
        var order = orderRaw != null ? orderRaw.ToString() : "0";
        var mainHeader = GetConstructorArgString(mainHeaderAttr, 0);

        // Get factory info from SettingUI attribute (ControlFactory is a Type, FactoryMethod is string)
        var factoryTypeArg = settingAttr?.NamedArguments.FirstOrDefault(a => a.Key == "ControlFactory").Value;
        var controlFactoryTypeName = factoryTypeArg?.Value is INamedTypeSymbol factType
            ? $"\"{factType.ToDisplayString()}\"" : "null";
        var factoryMethod = GetNamedArgString(settingAttr, "FactoryMethod");

        sb.AppendLine($"        private void Register_{safeName}()");
        sb.AppendLine("        {");
        sb.AppendLine("            var directProps = new List<PropertyDescriptor>();");
        sb.AppendLine("            var subSections = new List<SubSectionInfo>();");
        sb.AppendLine("            List<PropertyDescriptor>? currentSub = null;");
        sb.AppendLine("            string? currentSubTitle = null;");
        sb.AppendLine();

        foreach (var prop in GetPublicInstanceProperties(cls))
        {
            if (GetAttr(prop, HideAttributeName) != null) continue;

            var subHeaderAttr = GetAttr(prop, SubHeaderAttributeName);
            if (subHeaderAttr != null)
            {
                // Flush previous subsection
                sb.AppendLine("            if (currentSub != null && currentSubTitle != null)");
                sb.AppendLine("                subSections.Add(new SubSectionInfo(currentSubTitle, currentSub));");
                var subTitle = GetConstructorArgString(subHeaderAttr, 0) ?? $"\"{prop.Name}\"";
                sb.AppendLine($"            currentSubTitle = {subTitle};");
                sb.AppendLine("            currentSub = new List<PropertyDescriptor>();");
                continue;
            }

            var titleAttr = GetAttr(prop, TitleAttributeName);
            var displayName = GetConstructorArgString(titleAttr, 0) ?? $"\"{prop.Name}\"";

            var isEnum = prop.Type.TypeKind == TypeKind.Enum;

            // Range
            var rangeAttr = GetAttr(prop, RangeAttributeName);
            var hasRange = rangeAttr != null;
            var minVal = rangeAttr?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "0";
            var maxVal = rangeAttr?.ConstructorArguments.Length > 1 
                ? rangeAttr.ConstructorArguments[1].Value?.ToString() ?? "0" : "0";

            // ItemsSource
            var itemsSrcAttr = GetAttr(prop, ItemsSourceAttributeName);
            string? itemsSrcTypeName = null;
            string? itemsSrcPropName = null;
            if (itemsSrcAttr != null && itemsSrcAttr.ConstructorArguments.Length >= 2)
            {
                if (itemsSrcAttr.ConstructorArguments[0].Value is INamedTypeSymbol srcType)
                    itemsSrcTypeName = srcType.ToDisplayString();
                itemsSrcPropName = itemsSrcAttr.ConstructorArguments[1].Value?.ToString();
            }

            // ControlBinding
            var cbAttr = GetAttr(prop, ControlBindingAttributeName);
            string? cbTypeName = null;
            string? cbBindingProp = null;
            string? cbFactoryMethod = null;
            if (cbAttr != null)
            {
                if (cbAttr.ConstructorArguments.Length > 0 && cbAttr.ConstructorArguments[0].Value is INamedTypeSymbol cbType)
                    cbTypeName = cbType.ToDisplayString();
                cbBindingProp = GetNamedArgRaw(cbAttr, "BindingProperty");
                cbFactoryMethod = GetNamedArgRaw(cbAttr, "FactoryMethod");
            }

            var propTypeFqn = prop.Type.ToDisplayString();
            // For enum types, use the value as array via Enum.GetValues (generated code can still use static lookup)
            var enumValuesExpr = isEnum
                ? $"Array.ConvertAll(Enum.GetValues(typeof({propTypeFqn})), v => v.ToString() ?? string.Empty)"
                : "null";

            sb.AppendLine($"            var pd_{safeName}_{EscapeName(prop.Name)} = new PropertyDescriptor(");
            sb.AppendLine($"                \"{prop.Name}\",");
            sb.AppendLine($"                {displayName},");
            sb.AppendLine($"                \"{propTypeFqn}\",");
            sb.AppendLine($"                {(isEnum ? "true" : "false")},");
            sb.AppendLine($"                false,");
            sb.AppendLine($"                {(hasRange ? "true" : "false")},");
            sb.AppendLine($"                {minVal},");
            sb.AppendLine($"                {maxVal},");
            sb.AppendLine($"                {(itemsSrcTypeName != null ? $"\"{itemsSrcTypeName}\"" : "null")},");
            sb.AppendLine($"                {(itemsSrcPropName != null ? $"\"{itemsSrcPropName}\"" : "null")},");
            sb.AppendLine($"                {(cbTypeName != null ? $"\"{cbTypeName}\"" : "null")},");
            sb.AppendLine($"                {(cbBindingProp != null ? $"\"{cbBindingProp}\"" : "null")},");
            sb.AppendLine($"                {(cbFactoryMethod != null ? $"\"{cbFactoryMethod}\"" : "null")});");

            var varName = $"pd_{safeName}_{EscapeName(prop.Name)}";
            sb.AppendLine($"            if (currentSub != null) currentSub.Add({varName}); else directProps.Add({varName});");
            sb.AppendLine();
        }

        // Flush last subsection
        sb.AppendLine("            if (currentSub != null && currentSubTitle != null)");
        sb.AppendLine("                subSections.Add(new SubSectionInfo(currentSubTitle, currentSub));");
        sb.AppendLine();
        sb.AppendLine("            var descriptor = new SettingClassDescriptor(");
        sb.AppendLine($"                \"{fqn}\",");
        sb.AppendLine($"                \"{cls.Name}\",");
        sb.AppendLine($"                {mainHeader},");
        sb.AppendLine($"                {category},");
        sb.AppendLine($"                {order},");
        sb.AppendLine("                directProps,");
        sb.AppendLine("                subSections,");
        sb.AppendLine($"                {controlFactoryTypeName},");
        sb.AppendLine($"                {factoryMethod});");
        sb.AppendLine($"            _descriptors[\"{fqn}\"] = descriptor;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static IEnumerable<IPropertySymbol> GetPublicInstanceProperties(INamedTypeSymbol cls)
        => cls.GetMembers()
              .OfType<IPropertySymbol>()
              .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

    private static AttributeData? GetAttr(ISymbol symbol, string name)
        => symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == name);

    private static string? GetConstructorArgString(AttributeData? attr, int index)
    {
        if (attr == null || attr.ConstructorArguments.Length <= index) return null;
        var val = attr.ConstructorArguments[index].Value;
        return val != null ? $"\"{EscapeString(val.ToString()!)}\"" : "null";
    }

    private static string? GetNamedArgString(AttributeData? attr, string key)
    {
        if (attr == null) return null;
        foreach (var na in attr.NamedArguments)
        {
            if (na.Key == key)
            {
                var val = na.Value.Value;
                return val != null ? $"\"{EscapeString(val.ToString()!)}\"" : "null";
            }
        }
        return "null";
    }

    private static string? GetNamedArgRaw(AttributeData? attr, string key)
    {
        if (attr == null) return null;
        foreach (var na in attr.NamedArguments)
        {
            if (na.Key == key)
                return na.Value.Value?.ToString();
        }
        return null;
    }

    /// <summary>Makes a C# identifier safe by replacing special characters with underscores.</summary>
    private static string EscapeName(string name)
        => name.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
