<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAotCompatible>true</IsAotCompatible>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AutoSettingUI.Core\AutoSettingUI.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AutoSettingUI.Generator\AutoSettingUI.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
