<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AssemblyName>AutoSettingUI.WPF.Demo</AssemblyName>
        <RootNamespace>AutoSettingUI.WPF.Demo</RootNamespace>
        <IsPackable>false</IsPackable>


    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AutoSettingUI.Generator\AutoSettingUI.Generator.csproj" />
        <ProjectReference Include="..\..\src\Extensions\AutoSettingUI.WPF\AutoSettingUI.WPF.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    </ItemGroup>

</Project>
