<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <IsAotCompatible>true</IsAotCompatible>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <NoWarn>$(NoWarn);IL2026;IL2057;IL2067;IL2070;IL2072;IL2075;IL2104;IL3050</NoWarn>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>

        <PublishAot>true</PublishAot>
        <SelfContained>true</SelfContained>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>link</TrimMode>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.7"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.2.7"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.7"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.7"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.7">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="Irihi.Ursa" Version="1.13.0" />
        <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="1.13.0" />
        <PackageReference Include="Semi.Avalonia" Version="11.2.1.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\AutoSettingUI.Generator\AutoSettingUI.Generator.csproj"
                        OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\..\src\Extensions\AutoSettingUI.Ursa\AutoSettingUI.Ursa.csproj"
                        RemoveProperties="PublishAot" />
    </ItemGroup>

    <!-- Generator: project reference for normal builds, prebuilt analyzer for AOT publish -->
<!--    <ItemGroup Condition="'$(PublishAot)' != 'true'">-->
<!--      <ProjectReference Include="..\..\src\AutoSettingUI.Generator\AutoSettingUI.Generator.csproj"-->
<!--                        OutputItemType="Analyzer"-->
<!--                        ReferenceOutputAssembly="false" />-->
<!--    </ItemGroup>-->

<!--    <ItemGroup Condition="'$(PublishAot)' == 'true'">-->
<!--      <Analyzer Include="..\..\src\AutoSettingUI.Generator\bin\Release\netstandard2.0\AutoSettingUI.Generator.dll" />-->
<!--    </ItemGroup>-->
</Project>
